config/routes.rb
Rails.application.routes.draw do
  resources :order_product_mappings
  resources :orders
  resources :inventories
  resources :customers
  resources :distributors
  resources :products
  resources :manufacturers
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.present?
      if user.admin?
        can :manage, :all
      elsif user.employee?
        can :read, :all
        cannot :read, [Role, UserRoleMapping, User]
        can [:update, :read], User, id: user.id 
      end

    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/distributor.rb
class Distributor < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :product
  belongs_to :distributor
  belongs_to :manufacturer
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validate :checkForNameRegex

    def checkForNameRegex
        if Manufacturer.where('lower(name) like ?', "%#{name.downcase}%").present?
            errors.add(:name, "Name already present")
            return false
        end
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_product_mappings
  has_many :products, through: :order_product_mappings
end

app/models/order_product_mapping.rb
class OrderProductMapping < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :manufacturer
  has_many :order_product_mappings
  has_many :orders, through: :order_product_mappings
end

app/models/role.rb
class Role < ApplicationRecord
    validates :name, presence: true, uniqueness: true 

    has_many :user_role_mappings
    has_many :users, through: :user_role_mappings

    def add_role(user)
        user.add_role(self)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :lockable, :trackable

    has_many :user_role_mappings
    has_many :roles, through: :user_role_mappings

    # check whether user has the role
    def has_role?(role)
      roles.any? { |r| r.name.underscore.to_sym == role.to_sym}
    end

    def admin?
      has_role? (:admin)
    end

    def employee?
      has_role? (:employee)
    end

    def add_role(roleObj)
      return if roleObj.nil? || has_role?(roleObj.name)
      
      UserRoleMapping.create(user: self, role: roleObj)
    end
end

app/models/user_role_mapping.rb
class UserRoleMapping < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/admin_controller.rb
class AdminController < ActionController
end

app/controllers/distributors_controller.rb
class DistributorsController < InheritedResources::Base

  private

    def distributor_params
      params.require(:distributor).permit(:code, :name, :address, :contact_person, :contact_number)
    end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/distributors/_form.html.erb
<%= form_with(model: distributor) do |form| %>
  <% if distributor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(distributor.errors.count, "error") %> prohibited this distributor from being saved:</h2>

      <ul>
        <% distributor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :contact_person %>
    <%= form.text_field :contact_person %>
  </div>

  <div class="field">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/distributors/edit.html.erb
<h1>Editing Distributor</h1>

<%= render 'form', distributor: @distributor %>

<%= link_to 'Show', @distributor %> |
<%= link_to 'Back', distributors_path %>

app/views/distributors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Distributors</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Address</th>
      <th>Contact person</th>
      <th>Contact number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @distributors.each do |distributor| %>
      <tr>
        <td><%= distributor.code %></td>
        <td><%= distributor.name %></td>
        <td><%= distributor.address %></td>
        <td><%= distributor.contact_person %></td>
        <td><%= distributor.contact_number %></td>
        <td><%= link_to 'Show', distributor %></td>
        <td><%= link_to 'Edit', edit_distributor_path(distributor) %></td>
        <td><%= link_to 'Destroy', distributor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Distributor', new_distributor_path %>

app/views/distributors/new.html.erb
<h1>New Distributor</h1>

<%= render 'form', distributor: @distributor %>

<%= link_to 'Back', distributors_path %>

app/views/distributors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @distributor.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @distributor.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @distributor.address %>
</p>

<p>
  <strong>Contact person:</strong>
  <%= @distributor.contact_person %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @distributor.contact_number %>
</p>

<%= link_to 'Edit', edit_distributor_path(@distributor) %> |
<%= link_to 'Back', distributors_path %>